name: app_lock_flutter



version: 1.0.4+6

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  win32: ^5.0.4   
  archive: ^3.3.7
  
  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  flutter_svg: ^2.0.6
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  get: ^4.6.5
  url_launcher: ^6.1.5
  installed_apps: ^1.3.1
  flutter_inappwebview: ^5.4.3+7
  app_settings: ^4.1.6
  device_apps: ^2.2.0
  lottie: ^2.4.0
  intl: ^0.18.1
  html: ^0.15.0
  permission_handler: ^10.2.0
  usage_stats: ^1.2.0
  flutter_switch: ^0.3.2
  change_app_package_name: ^1.1.0
  file: ^6.1.4
  pattern_lock:
  local_auth:
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:

  
  uses-material-design: true

 
  assets:
    - assets/images/
    - assets/jsonFiles/
  #   - images/a_dot_ham.jpeg

 
